### ISSUE TITLE
MPs data sheets currently empty except for header

### ISSUE THREAD

**Issue by ciderpunx** [UKParlDataSheets/UKParlDataSheets-Scripts#3]
Presumably because the API endpoint went empty:
http://data.parliament.uk/membersdataplatform/services/mnis/members/query/House=Commons/Addresses/

**Comment by jarofgreen** [comment]
Thanks ....

I should have used this oppertunity to build a catch in the software - if the end point is empty, just stop and don't erase the current data. That way, during an election cycle the old data would still be there. I'm going to leave this ticket open as I'll try and do that. (Was to busy at time, sorry.)

After the election, I also opened https://github.com/UKParlDataSheets/UKParlDataSheets-Scripts/issues/4

**Comment by jarofgreen** [comment]
Put in a check to catch no data.
