### ISSUE TITLE
Filter out ; at end of email addresses

### ISSUE THREAD

**Issue by jarofgreen** [UKParlDataSheets/UKParlDataSheets-Scripts#5]
One MP currently has that.

**Comment by jarofgreen** [comment]
Should have noted which one; I've just checked data and can't see it so I guess they fixed it data side.

**Comment by ciderpunx** [comment]
What seems to have happened is that I committed it, got halfway through making the PR and then got sidetracked. I saw a notif earlier which made me look and realize I'd not sent the PR. Heh.
